### ISSUE TITLE
How to configure giscus?

### ISSUE THREAD

**Issue by feiyangbeyond** [Junyi-99/hugo-theme-anubis2#24]
How to configure giscus? 

Or should I read hugo's documentation?

**Comment by Junyi-99** [comment]
Hey, thanks for using anubis2, here is the example config for giscus:

```toml
[params]
  GiscusRepo = "Junyi-99/Junyi-99.github.io"
  GiscusRepoId = "MDEwOlJlcG9zaXRvcnkzNDI4ODI3NzY="
  GiscusCategory = "Announcements"
  GiscusCategoryId = "DIC_kwDOFG_52M4CZZZF"
  GiscusLazyLoad = false
  GiscusDataMapping = "url"
  dateFormat = "January 2, 2006"
```

Each parameter is obtained from the `<script>` provided by Giscus.

<img width="1233" alt="image" src="https://github.com/Junyi-99/hugo-theme-anubis2/assets/14367694/4a60ccbf-aaed-43e3-9512-f7f4f38adcd9">
